### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by OlivierJM** [NatashaChuza/Random_Quote_Machine#4]
You are doing great Natasha, The code looks great overall, there are few things that can be improved but the best thing is that logic seems great.
Just some clean up that would be needed but you can set up something like prettier for that

any idea why you needed to put this one in quotes?
https://github.com/NatashaChuza/Random_Quote_Machine/blob/f5cd4d8bd63cd44b23eccb157733fac1b075555a/src/components/QuoteBox.js#L5

**Comment by OlivierJM** [comment]
Let me know what other feedback or help you will be interested in.

**Comment by NatashaChuza** [comment]
Thank you Olivier, I put the quotes around the quote property because I want the quotes to appear in quotes, lol, I am fetching the quotes as strings from the api so the quotes they originally come with are not being output.

**Comment by OlivierJM** [comment]
🙈 Yeahh why didn't I think of that. It's a quote so it should definitely be in quotes, it now makes sense.
